[package]
name = "alice_rs"
version = "0.1.0"
authors = ["Entenjaeger2 <Entenjaeger_2@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
either = "1.5.3"